### ISSUE TITLE
Bug: Couldn't play podcast

### ISSUE THREAD

**Issue by mdtrilby** [Sn8z/Poddr#363]
**Describe the bug**
At random intervals during podcast playback I get a red error message top right saying "Couldn't play podcast". The timer stops along with the audio. I can click the play/pause button, it changes the graphic between the modes, but playback doesn't continue. I have to restart the episode, which starts it from the beginning, it doesn't remember where it was.

**To Reproduce**
1. Go to any podcast episode
2. Click play
3. Wait for it to stop

**Expected behavior**
I expected it to continue playing.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 (latest stable)
 - Version: 1.1.0 Poddr

**Additional context**

**Comment by Sn8z** [comment]
Thanks for opening an issue @mdtrilby!

Could you provide some more information regarding what podcast you are trying to play? or does this happen with every podcast?

There's also a log file located at `%USERPROFILE%\AppData\Roaming\poddr\log.log` which shows the full error message, check it out when the error appears and post it back here 💃

**Comment by mdtrilby** [comment]
Hi! It happens with any podcast. Here's the full error message trying to play a podcast this morning: 

[2019-09-26 09:15:46.181] [info] Saved playerstate!
[2019-09-26 09:15:46.198] [info] Playing podcast.
[2019-09-26 09:15:46.210] [info] Started loading podcast...
[2019-09-26 09:15:47.894] [info] Can play through podcast.
[2019-09-26 09:22:41.906] [error] PIPELINE_ERROR_READ: FFmpegDemuxer: data source error

**Comment by Sn8z** [comment]
Hmm, sounds weird that this happens with every podcast you play.
Has this always been the case for you or have Poddr worked correctly before?
Could you tell me an example of a podcast you are trying to listen to that doesn't work?

I'm kinda struggling to reproduce this error on my end atm but I will do my best.

**Comment by Sn8z** [comment]
@mdtrilby any update on this issue? I could really need some more information to work with here.
I've just released a new version of Poddr so you can update and try again first if you want to.

**Comment by mdtrilby** [comment]
Hi! Yes, I've now tried also v2.0.0 and the same thing happens, any podcast.

Here's from the log: 
[2019-11-21 13:52:39.244] [error] Audio service :: Error => 2 :: PIPELINE_ERROR_READ: FFmpegDemuxer: data source error
[2019-11-21 13:52:39.259] [error] Audio service :: Audio source => http://dts.podtrac.com/redirect.mp3/chtbl.com/track/478G5/feeds.soundcloud.com/stream/715974202-mattwalshshow-ep375.mp3
[2019-11-21 13:52:39.272] [info] Toast service :: Showing error toast => A network error caused the audio download to fail.

I have really good network connection, though. 250Mbps. No other issues. I've tried to download the episode, and it seems to happen then, too...

**Comment by fionamorrison13** [comment]
Same issue here. This has not been fixed. I have an even greater network speed and I still fail to play anything more than 2-3 minutes of a podcast before I get that "A network error caused the audio download to fail" error.

**Comment by Sn8z** [comment]
The issue is open since it's not fixed yet, that's how an issue works.
There are multiple types of network errors not related to download speed and it doesn't have to be an error caused on your end. This is an issue that is hard to replicate and pin point, especially without any details...

- So @fionamorrison13 what version of Poddr are you using?
- What OS are you using?
- What podcast are you trying to listen to? Make sure that you try to listen to episodes from different podcasts hosted on different platforms. There are some known issues with episodes hosted on Soundcloud for example that are hard to find a good solution for since the connection sometimes drop for reasons unknown to me.
- If you download the episode where the error occurs make sure that you navigate to "Favourites" -> "Offline" and launch the episode from there, otherwise it wont look for the downloaded file at this point in time.

If you could provide a log like @mdtrilby did it would be great.

**Comment by fionamorrison13** [comment]
I'm sorry for the late reply! I've been really busy.
I'm using the latest version (2.0.0).
I'm using Windows 10.
I'm listening to "The Complete Privacy & Security Podcast" which is in fact hosted on Soundcloud.
Here are my logs:
[2021-01-18 21:01:34.921] [info] Audio service :: Playing.
[2021-01-18 21:02:23.079] [error] Audio service :: Error => 2 :: PIPELINE_ERROR_READ: FFmpegDemuxer: data source error
[2021-01-18 21:02:23.086] [error] Audio service :: Audio source => http://feeds.soundcloud.com/stream/287998035-user-98066669-001-the-complete-privacy-security-podcast.mp3
[2021-01-18 21:02:23.095] [info] Toast service :: Showing error toast => A network error caused the audio download to fail.

**Comment by Sn8z** [comment]
@fionamorrison13 No worries!
Yeah, that seems to be the same issue as other people have experienced aswell.
I'm still not sure as to why this happens, needs more investigating on my side 💃

**Comment by Sn8z** [comment]
Closing this issue since it seems to be stale.
Feel free to open a new issue if needed.
